integration_tests/Makefile, integration_tests/assets/docker-compose.documentation.override.yml, integration_tests/suite/test_documentation.py, integration_tests/test-requirements.txt, wazo_chatd/plugins/rooms/api.yml
fix openapi specification
use openapi-spec-validator instead of swagger-validator
=> Pull request for WAZO-840-openapi-spec-validator

alembic/versions/55c3b35d4b4c_add_channel_state_cache.py, integration_tests/suite/helpers/bus.py, integration_tests/suite/test_db_endpoint.py, integration_tests/suite/test_event_handler.py, wazo_chatd/bus.py, wazo_chatd/database/models.py, wazo_chatd/database/queries/endpoint.py, wazo_chatd/main.py, wazo_chatd/plugins/presences/bus_consume.py, wazo_chatd/plugins/presences/initiator.py
add find_or_create helper to endpoint dao
test: fix routing_key format
presence: force state to be like channel_state
listen on Newchannel and Hangup ami events
silence amqp logger
fix wrong constraint
=> Pull request for WAZO-1157-make-presence-more-robust

integration_tests/suite/helpers/bus.py, tox.ini, wazo_chatd/bus.py, wazo_chatd/plugins/presences/bus_consume.py
tox add make in whitelist command
fix tenant creation name
=> Pull request for fix-tenant-event-name

alembic/versions/55c3b35d4b4c_add_channel_state_cache.py, etc/wazo-chatd/config.yml, integration_tests/assets/etc/wazo-chatd/conf.d/50-default.yml, integration_tests/suite/helpers/amid.py, integration_tests/suite/helpers/bus.py, integration_tests/suite/test_db_refresh_token.py, integration_tests/suite/test_db_user.py, integration_tests/suite/test_event_handler.py, integration_tests/suite/test_presence_initialization.py, integration_tests/suite/test_presences.py, tox.ini, wazo_chatd/config.py, wazo_chatd/database/models.py, wazo_chatd/plugins/presences/bus_consume.py, wazo_chatd/plugins/presences/initiator.py, wazo_chatd/plugins/presences/tests/test_schemas.py
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/30
=> use amid without ssl by default

etc/wazo-chatd/config.yml, integration_tests/assets/etc/wazo-chatd/conf.d/50-default.yml, wazo_chatd/config.py
Depends-on:https://github.com/wazo-platform/xivo-test-helpers/pull/31
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1689
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1689
=> use auth http instead https

etc/wazo-chatd/config.yml, wazo_chatd/config.py
reason: consul is configured to http
=> remove irrelevant verify consul option

integration_tests/suite/helpers/bus.py, integration_tests/suite/test_presence_initialization.py
reason: id has been replaced by uuid
=> use endpoint_sip uuid

contribs/docker/Dockerfile-db, integration_tests/assets/docker-compose.documentation.override.yml, integration_tests/suite/conftest.py, integration_tests/suite/helpers/base.py, integration_tests/suite/test_config.py, integration_tests/suite/test_db_channel.py, integration_tests/suite/test_db_endpoint.py, integration_tests/suite/test_db_line.py, integration_tests/suite/test_db_presence_initiator.py, integration_tests/suite/test_db_refresh_token.py, integration_tests/suite/test_db_room.py, integration_tests/suite/test_db_session.py, integration_tests/suite/test_db_tenant.py, integration_tests/suite/test_db_user.py, integration_tests/suite/test_documentation.py, integration_tests/suite/test_event_handler.py, integration_tests/suite/test_presence_initialization.py, integration_tests/suite/test_presences.py, integration_tests/suite/test_room_message.py, integration_tests/suite/test_status.py, integration_tests/suite/test_user_room.py
refactor int test to use pytest fixtures
reason improve speed 
On my machine: from 5min51 to 2min32
=> Pull request for improve-tests-speed

Dockerfile, debian/wazo-chatd.service, etc/wazo-chatd/config.yml, wazo_chatd/config.py, wazo_chatd/main.py
reason: systemd restart remove monit usage based on pid file
=> remove usage of PID file and use systemd options

alembic/versions/6ba500c45fcc_add_dnd_to_presence.py, integration_tests/suite/helpers/bus.py, integration_tests/suite/test_db_presence_initiator.py, integration_tests/suite/test_db_user.py, integration_tests/suite/test_event_handler.py, integration_tests/suite/test_presence_initialization.py, integration_tests/suite/test_presences.py, wazo_chatd/bus.py, wazo_chatd/database/models.py, wazo_chatd/plugins/presences/api.yml, wazo_chatd/plugins/presences/bus_consume.py, wazo_chatd/plugins/presences/initiator.py, wazo_chatd/plugins/presences/schemas.py
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/136
=> WAZO-1809: add do not disturb to user presence

integration_tests/suite/helpers/bus.py, integration_tests/suite/test_presence_initialization.py
reason: id has been replaced by uuid
=> WAZO-1913 - use endpoint_sip uuid

wazo_chatd/bus.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/30
=> bus: use correct policy for publishing

CHANGELOG.md, integration_tests/suite/test_presences.py, wazo_chatd/plugins/presences/api.yml, wazo_chatd/plugins/presences/schemas.py
=> add new connected attribute to presence

CHANGELOG.md, integration_tests/suite/test_event_handler.py, integration_tests/suite/test_presences.py, wazo_chatd/plugins/presences/api.yml, wazo_chatd/plugins/presences/schemas.py
Depends-on: https://github.com/wazo-platform/wazo-chatd/pull/33
=> Pull request for WAZO-1319-add-connected-attribute

wazo_chatd/config.py
=> set pg application_name

CHANGELOG.md, integration_tests/suite/helpers/wait_strategy.py, wazo_chatd/auth.py, wazo_chatd/controller.py, wazo_chatd/plugins/status/api.yml
why: avoid false positive in integration test
=> add status of master_tenant initialization

integration_tests/suite/helpers/base.py, integration_tests/suite/test_presence_initialization.py, integration_tests/test-requirements-for-tox.txt
why: to have the latest docker-compose
=> use docker-compose from binary instead of python

integration_tests/suite/helpers/base.py, integration_tests/suite/test_config.py, tox.ini
test: An environment variable added for test_restrict_on_with_slow_wazo_auth
=> test: add environment variable for auth tries

requirements.txt, wazo_chatd/plugins/presences/schemas.py, wazo_chatd/plugins/rooms/schemas.py
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/93
=> Wazo-2638: Migration of wazo-chatd from Marshmallow 3.0.0b14 to stable version 3.10.0

integration_tests/suite/helpers/base.py, integration_tests/suite/test_event_handler.py, integration_tests/suite/test_presences.py, integration_tests/suite/test_room_message.py, integration_tests/suite/test_user_room.py, wazo_chatd/bus.py, wazo_chatd/controller.py, wazo_chatd/plugins/presences/notifier.py, wazo_chatd/plugins/rooms/notifier.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/59
=> WAZO-2505: chatd events

CHANGELOG.md, integration_tests/suite/test_db_room.py, integration_tests/suite/test_user_room.py, wazo_chatd/database/queries/room.py, wazo_chatd/plugins/api/api.yml, wazo_chatd/plugins/presences/api.yml, wazo_chatd/plugins/presences/schemas.py, wazo_chatd/plugins/presences/tests/test_schemas.py, wazo_chatd/plugins/rooms/api.yml, wazo_chatd/plugins/rooms/http.py, wazo_chatd/plugins/rooms/schemas.py
Depends-on: https://github.com/wazo-platform/wazo-chatd-client/pull/10
=> Pull request for WAZO-2936-room-user-uuid-query

wazo_chatd/plugins/teams_presence/bus_consume.py, wazo_chatd/plugins/teams_presence/services.py, wazo_chatd/plugins/teams_presence/subscriptions.py
* Fix race condition with external auth (by retrying 3 times in case of failure)
* Fix typo in resource name (missing a 's')
* Added more debug information
=> Fix teams integration

wazo_chatd/plugins/api/api.yml
depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/613
=> [WAZO-3270] Add logo to spec

integration_tests/Dockerfile-chatd
https://wazo-dev.atlassian.net/browse/WAZO-3342
=> Updated integration test dockerfile editable install commands

integration_tests/suite/test_user_room.py, wazo_chatd/database/queries/room.py, wazo_chatd/plugins/rooms/http.py
why: it was impossible to create a chat room with subset of participants
if a bigger group existed
=> room: fix subset create when group exists

wazo_chatd/http.py, wazo_chatd/http_server.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/141
=> Pull request for WP-1540-module-auth-verifier-refactor

integration_tests/suite/helpers/base.py, integration_tests/suite/test_config.py
why: because verify decorators have been reordered, testing this
scenario is much more harder. The token is now verified and if wazo-auth
is down, we will always get server unareachable. So testing with a
invalid-service token ensure to raise this error
=> test: refactor not-initialized tests

debian/wazo-chatd.dirs, debian/wazo-chatd.service, etc/rsyslog.d/99-wazo-chatd.conf
=> WAZO-3682: disable logs in rsyslog

wazo_chatd/http_server.py
=> HTTP server: apply cheroot patch

.dockerignore, integration_tests/suite/helpers/bus.py, integration_tests/suite/test_presence_initialization.py, wazo_chatd/plugins/presences/bus_consume.py, wazo_chatd/plugins/presences/initiator.py, wazo_chatd/plugins/presences/initiator_thread.py, wazo_chatd/plugins/presences/plugin.py, wazo_chatd/plugins/presences/tests/test_bus_consume.py
=> [WAZO-3931] presences: restart initiator_thread on asterisk boot

integration_tests/suite/helpers/base.py, integration_tests/suite/helpers/confd.py, integration_tests/suite/helpers/wait_strategy.py, integration_tests/suite/test_presence_initialization.py, wazo_chatd/bus.py, wazo_chatd/plugins/presences/bus_consume.py, wazo_chatd/plugins/presences/initiator.py, wazo_chatd/plugins/presences/plugin.py
Depends-on: https://github.com/wazo-platform/wazo-test-helpers/pull/119
=> WAZO-4175-event-during-init

.pre-commit-config.yaml, Dockerfile, debian/control, integration_tests/Dockerfile-db, integration_tests/Makefile, integration_tests/assets/docker-compose.yml, integration_tests/docker/Dockerfile-microsoft-mock, integration_tests/suite/test_db_user.py, pyproject.toml, requirements.txt, tox.ini, wazo_chatd/plugins/teams_presence/bus_consume.py, wazo_chatd/plugins/teams_presence/services.py, zuul.yaml
- **bullseye -> bookworm**
- **requirements: bump to bookworm**
- **pyupgrade 3.9 -> 3.11**
- **fixup! bullseye -> bookworm**
- **integration_tests: cleanup db overrides**
- **teams: fix asyncio api change**
=> WAZO 4277 bookworm
