wazo-platform/wazo-chatd

- Dockerfile
- debian/wazo-chatd.service
- etc/wazo-chatd/config.yml
- wazo_chatd/config.py
since buster /var/run is a now a symlink to /run
> use /run instead of /var/run

- integration_tests/suite/test_db_user.py
- wazo_chatd/database/queries/user.py
Since session and refresh_token do not have any objects related, we
can easily replace them if we receive a second created event.
For other resources like tenant, user and line, it is a little bit more
risky. Because if we replace the resource, then every resources releated
to it will be removed
> replace session/token if 2 events created events are sent

- etc/wazo-chatd/config.yml
- wazo_chatd/config.py
reason: It doesn't mind if the request is long, it's only used one time
for initialisation.
> increate confd default timeout to 90

- integration_tests/suite/test_db_presence_initiator.py
- integration_tests/suite/test_db_refresh_token.py
- wazo_chatd/database/queries/refresh_token.py
- wazo_chatd/plugins/presences/initiator.py
reason: some service users can have a refresh token and it should not
impact wazo-chatd
> presence: fix when token belong to non pbx user

- debian/wazo-chatd.service
reason: to see the daemon name in the journalctl/syslog instead of
`python3`
> debian: add SyslogIdentifier on service file

- etc/wazo-chatd/config.yml
- integration_tests/assets/etc/wazo-chatd/conf.d/50-default.yml
- integration_tests/suite/helpers/confd.py
- wazo_chatd/config.py
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/32
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1747
> use confd without ssl by default

- Dockerfile
- integration_tests/Dockerfile-chatd
- integration_tests/assets/etc/wazo-chatd/conf.d/50-default.yml
- integration_tests/suite/test_presences.py
docker: use multi stage build
reason:
* original layer slim-buster: 155MB
* without multi-stage: 282MB = wazo layers: 127MB
* with multi-stage: 221MB = wazo layers: 66MB
It reduces wazo weight by 52% for pure python dependencies. For services that
need to compile their deps, it will be much higher
> Pull request for reduce-docker-image

- integration_tests/suite/helpers/base.py
reason: loggers already silenced by xivo-test-helpers
> test: remove silence logger

- integration_tests/suite/test_db_user.py
- integration_tests/suite/test_presences.py
- wazo_chatd/database/queries/user.py
- wazo_chatd/exceptions.py
reason: when listing users with wrong filter, we should return empty
result instead of error code
> avoid to return 404 on unknown uuid from query string

- wazo_chatd/plugins/presences/initiator_thread.py
Why:
* When the machine starts, wazo-auth may take some time to answer
* requests Timeout is not a ConnectionError or a HTTPError
> intiator: catch timeout errors

- wazo_chatd/plugin_helpers/tenant.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/60
reason: when using recurse=True, flask helpers already fetch tenants. So
instead to fetch list twice, we use the same list
> use flask helpers to avoid duplicate requests

- integration_tests/suite/test_event_handler.py
- wazo_chatd/plugins/presences/initiator.py
reason: allow to distinguish caller and callee. It allows to make logic
only on the phone that receive a call (ex: call pickup). For now, we cannot add a
new state to keep compatibility with external applications
But should be done in a future release
> presence: change ringing to talking for the caller

- integration_tests/assets/docker-compose.yml
- integration_tests/assets/etc/wazo-chatd/conf.d/50-default.yml
- integration_tests/assets/key-file.yml
- integration_tests/suite/helpers/base.py
- integration_tests/suite/test_config.py
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/53
Note: to pass integration tests
* build wazo-auth-mock
* use `WAZO_TEST_NO_DOCKER_COMPOSE_PULL=1` variable
> Pull request for avoid-hardcoded-token-test

- integration_tests/suite/helpers/bus.py
- integration_tests/suite/test_event_handler.py
- integration_tests/suite/test_presences.py
- integration_tests/suite/test_room_message.py
- integration_tests/suite/test_user_room.py
- wazo_chatd/plugins/presences/notifier.py
- wazo_chatd/plugins/rooms/notifier.py
Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/69
The idea is to inject tenant_uuid in all bus events, so that messages can be filtered by tenant when exiting the stack to external apis
> WAZO-2499 Adds tenant_uuid to bus event headers

- wazo_chatd/controller.py
Reason: Our other services have this injection, and it's very useful for creating modules who need to have access to other services with our python clients.
> [WAZO-2709] Inject token renewer for modules

- CHANGELOG.md
- alembic/env.py
- alembic/versions/d39356de87a3_database_add_timezone_to_dates.py
- integration_tests/suite/test_db_user.py
- wazo_chatd/database/models.py
Why:
* Easer to test upgrades on a remote machine
Why:
* So that API consumer do not need to worry about timezone
> Pull request for WAZO-2760-api-datetime-with-timezone

- integration_tests/suite/test_db_presence_initiator.py
- integration_tests/test-requirements-for-tox.txt
- test-requirements.txt
- wazo_chatd/plugins/presences/tests/test_schemas.py
- wazo_chatd/tests/test_controller.py
why: pypi version is a backport if the python3 builtin package
> test: use mock from unittest library

- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/wait_strategy.py
- integration_tests/suite/test_config.py
- integration_tests/suite/test_documentation.py
- integration_tests/suite/test_presence_initialization.py
why: since docker-compose project base name depends from asset name, we
must have one asset by *IntegrationTest class
why: avoid explicit logic to reset client after restart
> Pull request for fix-generated-project-name

- wazo_chatd/plugins/rooms/api.yml
why: message field doesn't exist
> fix wrong openapi spec for room

- integration_tests/suite/helpers/base.py
why: need to remove session before stopping postgres to avoid to leave
DB corrupt and be longer to boot. Moreover, we also need to remove
scoped_session to be able to recreate a valid cls._Session.
We were only lucky that no more test need this helper, because it
wouldn't work
And add small helper to be sure db is up, when it takes longer time to
boot (ex: when DB is corrupted).
> tests: fix flaky presence init tests

- integration_tests/suite/test_event_handler.py
- integration_tests/suite/test_presences.py
- wazo_chatd/plugins/presences/notifier.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/75
Modify PresenceUpdatedEvent to be broadcasted inside the tenant instead of sent to the targeted user.
> WAZO-2900: Fix presence broadcast

- integration_tests/suite/helpers/base.py
why: restarting postgres test was failing because postgres was too long
to restart. It was very slow because it was not well closed and the DB
performed a safe check. DB wasn't well closed because a connection was
still alive (idle) and the smart shutdown[1] was not done correctly
Since engine is created with autocommit=False (default value), As
soon we call Session.remove(), another transaction is immediately
begun[2].
To avoid this behavior, we can dispose of the connection pool before and
remove any existing transaction, thus no other transaction could be
created
1. https://www.postgresql.org/docs/current/server-shutdown.html
2. https://docs.sqlalchemy.org/en/12/orm/session_api.html#sqlalchemy.orm.session.Session.close
3. https://docs.sqlalchemy.org/en/12/core/connections.html?highlight …
> test: dispose connection before stopping postgres

- wazo_chatd/plugins/presences/schemas.py
- wazo_chatd/plugins/rooms/schemas.py
- wazo_chatd/plugins/rooms/tests/test_schemas.py
why: instantiate list in the schema definition will reuse same object
for all requests. Since we update this object in the http.py, it causes
issue. We need to have a new list object at each call
why: avoid side effect when code modify it
note: These objects don't have issue, only to be future proof
> Pull request for WAZO-2953-regression-get-chat-room

- wazo_chatd/plugins/teams_presence/services.py
- wazo_chatd/plugins/teams_presence/subscriptions.py
Why:
* If we get 401, it means our user token's is expired, When expired, auth will automatically fetch a new access token for us
> refresh user's token if we get 401

- CHANGELOG.md
- integration_tests/suite/test_user_room.py
- wazo_chatd/plugins/rooms/api.yml
- wazo_chatd/plugins/rooms/http.py
change the limitation of UserRoom Length from equal=2 to min=2,max=100,
add test_create_group test,
change test_create_with_wrong_users_number to pass the new validation rule,
change the _assert_create_raise_400_users_error to check the constraint rule
> WAZO-2995 Group chat functionality

- wazo_chatd/plugins/presences/bus_consume.py
- wazo_chatd/plugins/presences/initiator.py
- wazo_chatd/plugins/presences/tests/test_bus_consume.py
we do not need to track hints for chatd to work, at the moment more hints are stored in the db then endpoints. updating the hints also adds pressure on the database that updates their statuses not no reason
> device state change: ignore hints

- integration_tests/suite/test_teams_presence.py
- wazo_chatd/plugins/teams_presence/services.py
This PR fixes 2 issues with the teams connector:
1. Prevents the `line is unavailable` issue when status is offline
2. Removes the ability to be set to invisible by Teams
(If unsure how to test, send me a message)
> WP-1225: Teams fix line unavailable and remove invisible status

- integration_tests/suite/test_event_handler.py
- wazo_chatd/config.py
- wazo_chatd/plugins/presences/bus_consume.py
- wazo_chatd/plugins/presences/initiator.py
- wazo_chatd/plugins/presences/initiator_thread.py
- wazo_chatd/plugins/presences/tests/test_bus_consume.py
- wazo_chatd/plugins/presences/tests/test_initiator.py
**presence: filter all non pjsip/sccp devices**
why: We only want to track event for PJSIP/SCCP endpoints
**initialization: use pagination to fetch resources**
why: avoid to reach timeout
**initialization: use different strategy on ReadTimeout**
why: The main reasons to have ReadTimeout are:
* service is under heavy load
* too much resource and service will ALWAYS raise ReadTimeout
Solutions:
- Use different retry_time to let the system decrease its load
- stop wazo-chatd after 12 min (arbitrary among of time that should be enough
to have a "big" system stable after wazo-service restart)
- add unittests for paginate logic (IMHO integration tests would be overkill)
- Fix integration tests / mock calls
Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/101
> Pull request for WP-1324-paginate-init

- wazo_chatd/plugins/rooms/services.py
why: logic was reverted in the PR
> remove unused code

- integration_tests/assets/microsoft_graphql/mock_microsoft.py
- wazo_chatd/plugins/teams_presence/http.py
- wazo_chatd/plugins/teams_presence/schemas.py
- wazo_chatd/plugins/teams_presence/services.py
- wazo_chatd/plugins/teams_presence/subscriptions.py
MS Subscription API changes breaks the current implementation of presence synchronization.  
The presence information is no longer conveyed with the push notification message by default (unless you subscribe with an encryption certificate)
This PR changes the plugin's mechanic by `GET`ting the presence information when it receives a presence change webhook
> WAZO-3927: fix teams presence for MS API change

- requirements.txt
- wazo_chatd/plugins/presences/schemas.py
- wazo_chatd/plugins/rooms/schemas.py
- wazo_chatd/plugins/teams_presence/schemas.py
This change uses the Bookworm version of marshmallow to reduce the scope of changes that are going to happen when doing the upgrade
> Use marshmallow version 3.18.0 from Bookworm

- integration_tests/Dockerfile-db
- integration_tests/Makefile
- integration_tests/assets/docker-compose.yml
Why:
* Allows debugging race conditions issues
> integration-tests: log all DB statements

- wazo_chatd/plugins/presences/bus_consume.py
Since we have a catch Exception in the event handler thread, this
traceback doesn't cause any issue. But create bad log... So adding a
check on the callback before getting attribute will ignore "unsupported"
callbacks
> fix-unhandled-event-during-init
